From `focalboard` to `board` to generate tar bundle
mattermost/mattermost-plugin-boards pull request #14
Opened 2024-07-25 14:07 UTC by Rajat-Dabade

Build name
Previous : `focalboard-<version>.tar.gz`
Now: `board-<version>.tar.gz`

2024-07-25 14:24 UTC, M-ZubairAhmed approved these changes

2024-07-25 16:04 UTC, marianunez requested changes

2024-07-25 16:04 UTC, marianunez commented on Makefile
> +PLUGIN_NAME=board
Should be `Boards` plural

```suggestion
PLUGIN_NAME=boards
```

2024-07-26 04:47 UTC, harshilsharma63 approved these changes
Other than the comment Maria mentioned, that it should be plural `boards` instead of singular `board`, everything else looks good.

2024-07-27 11:02 UTC, Rajat-Dabade commented on Makefile
> +PLUGIN_NAME=board
Done.

2024-07-27 15:39 UTC, marianunez commented on Makefile
> +BOARD_PLUGIN_PATH=$(MATTERMOST_PLUGINS_PATH)/board
```suggestion
BOARD_PLUGIN_PATH=$(MATTERMOST_PLUGINS_PATH)/boards
```

2024-07-27 15:42 UTC, Rajat-Dabade commented on Makefile
> +BOARD_PLUGIN_PATH=$(MATTERMOST_PLUGINS_PATH)/board
Ah, missed it. Nice catch 🙌

2024-07-27 15:42 UTC, marianunez approved these changes

2024-07-27 17:50 UTC, merged