[MM-58805]: Remove Standalone code
mattermost/mattermost-plugin-boards pull request #2
Opened 2024-06-27 13:49 UTC by Rajat-Dabade

The PR mainly focus on removing standalone code which include
- isPlugin

2024-06-28 12:43 UTC, Rajat-Dabade commented on Makefile
> +info: ## Display build information
This was only added for debugging purposes. Will remove this after the plugin becomes stable. 
Created the issue to track this down: https://github.com/mattermost/mattermost-plugin-boards/issues/3

2024-07-05 04:17 UTC, harshilsharma63 requested changes
Look fine overall but we need to keep those guest user checks as they are still needed in plugin. For example, a guest user in Mattermost shouldn't be allowed to access all the templates.

2024-07-05 04:46 UTC, Rajat-Dabade commented on server/api/archive.go
> -	isGuest, err := a.userIsGuest(userID)
Reverted back.

2024-07-05 04:46 UTC, Rajat-Dabade commented on server/api/archive.go
> -	isGuest, err := a.userIsGuest(userID)
Done.

2024-07-09 13:44 UTC, sbishel approved these changes
Looks good. I believe all the Cypress tests run in Standalone code. I don't see any updates for those here. So I would expect those to fail.

2024-07-16 16:39 UTC, marianunez approved these changes

2024-07-30 07:58 UTC, merged