MM-61822 Fix the boards LHS and channel RHS boards channel memeber permission issue.
mattermost/mattermost-plugin-boards pull request #37
Opened 2024-11-18 09:08 UTC by Rajat-Dabade

#### Summary
This PR addresses a regression where channel members could not see boards linked to the channel in the channel's board RHS or the boards LHS. The issue occurred because boards only checked for board membership, which previously relied on `Mattermost's auth layer`. When the auth layer was removed during the plugin refactoring, the related code was lost.

- https://github.com/mattermost-community/focalboard/blob/de5e5cc4141f14f69bf0e5666383997b81f851d6/server/services/store/mattermostauthlayer/mattermostauthlayer.go#L1052
- https://github.com/mattermost-community/focalboard/blob/de5e5cc4141f14f69bf0e5666383997b81f851d6/server/services/store/mattermostauthlayer/mattermostauthlayer.go#L1101

This fix ensures channel members can now see linked boards in both the channel RHS and the boards LHS. Additionally, I reviewed the removed `Mattermost auth layer` code and restored all the missing functionality in this PR.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-61822

2024-11-19 04:01 UTC, harshilsharma63 requested changes

2024-11-19 04:01 UTC, harshilsharma63 commented
Other than the one comment, it works perfectly locally.

2024-11-19 04:03 UTC, harshilsharma63 requested changes
Can you also add tests for this on store and app level?

2024-11-19 07:28 UTC, Rajat-Dabade commented on server/services/store/sqlstore/board.go
> +	if user.IsGuest {
At this point, `member` contains only `explicitMembers,` but yes, you are correct that it should be moved before fetching the synthetic board members. 

Done ✅

2024-11-19 08:43 UTC, Rajat-Dabade commented
>Can you also add tests for this on store and app level?

@harshilsharma63 Server tests are not configured yet in this repo because it was causing some issues (related to the plugin which needs MM table migration), Maybe this open source Friday I will look into this and then I can add a test for these file changes as well.

2024-11-19 16:43 UTC, hmhealey commented
> > Can you also add tests for this on store and app level?
> 
> @harshilsharma63 Server tests are not configured yet in this repo because it was causing some issues (related to the plugin which needs MM table migration), Maybe this open source Friday I will look into this and then I can add a test for these file changes as well.

Would those tests possibly have caught this issue before? If we aren't able to run existing tests, that seems like something we should see about getting you some non-OSF time to work on

2024-11-19 16:50 UTC, hmhealey approved these changes
It's pretty weird to me that the old code handled explicit and implicit members in separate packages there. I would've expected that to be done in one place, but I guess there were good reasons to do that. I notice that we seem to also be mixing the terms "implicit" and "synthetic" for those as well, but those both sound nicer than the "fake" channels term that we use in the web app 😛

This looks good to me, although the lack of tests for this code is concerning

2024-11-19 16:50 UTC, hmhealey commented on server/services/store/sqlstore/board.go
> +	newQuery := s.getQueryBuilder(db).
Could you change this name to something more descriptive like `implicitMembersQuery`?

2024-11-19 20:00 UTC, yasserfaraazkhan approved these changes

2024-11-20 00:30 UTC, harshilsharma63 approved these changes

2024-11-20 14:02 UTC, Rajat-Dabade commented
@hmhealey I will try to fix the server test issue in this OSF.

2024-11-20 14:04 UTC, merged